# Generated by Django 5.1.7 on 2025-03-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagitech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BananaScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ripeness_level', models.IntegerField()),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
