# Generated by Django 5.1.7 on 2025-03-29 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagitech', '0002_bananascan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(choices=[('north', 'North Field'), ('east', 'East Field'), ('south', 'South Field'), ('west', 'West Field'), ('all', 'All Fields')], default='all', max_length=10)),
                ('reminder', models.CharField(choices=[('none', 'No Reminder'), ('same', 'Same Day'), ('1day', '1 Day Before'), ('3days', '3 Days Before'), ('1week', '1 Week Before')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BananaScan',
        ),
    ]
